# Generated by Django 5.0.7 on 2024-07-19 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='created_add',
            new_name='created_at',
        ),
    ]
